package com.canary.ui.screens

import android.graphics.Bitmap
import android.nfc.NfcAdapter
import android.nfc.Tag
import androidx.compose.foundation.Image
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.animation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.canary.MainActivity
import com.canary.data.PreferencesManager
import com.canary.service.CryptoService
import com.canary.service.NfcService
import com.canary.ui.theme.Green80

enum class SetupStep {
    WELCOME,
    GENERATE_KEY,
    GITHUB_CONFIG,
    PAIR_TAG,
    QR_BACKUP,
    DONE,
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SetupScreen(
    nfcService: NfcService,
    cryptoService: CryptoService,
    prefsManager: PreferencesManager,
    onSetupComplete: () -> Unit,
) {
    var step by remember { mutableStateOf(SetupStep.WELCOME) }
    var keyGenerated by remember { mutableStateOf(cryptoService.isKeyGenerated()) }
    var repoOwner by remember { mutableStateOf("") }
    var repoName by remember { mutableStateOf("") }
    var githubPat by remember { mutableStateOf("") }
    var tagPaired by remember { mutableStateOf(false) }
    var nfcMessage by remember { mutableStateOf("") }

    Scaffold { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
        ) {
            when (step) {
                SetupStep.WELCOME -> {
                    Text("Canary", style = MaterialTheme.typography.displayLarge)
                    Spacer(Modifier.height(8.dp))
                    Text("Proof-of-life canary system", style = MaterialTheme.typography.bodyLarge)
                    Spacer(Modifier.height(32.dp))
                    Text(
                        "This app pairs with an RFID sticker. Tap it daily to " +
                        "prove you're alive. Each canary is signed with your " +
                        "private key and anchored to the Bitcoin blockchain.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(32.dp))
                    Button(onClick = { step = SetupStep.GENERATE_KEY }) {
                        Text("Start Setup")
                    }
                }

                SetupStep.GENERATE_KEY -> {
                    Text("Generate Signing Key", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "A unique Ed25519 keypair will be created and stored " +
                        "in your device's hardware-backed keystore. This key " +
                        "never leaves your phone.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(24.dp))

                    if (!keyGenerated) {
                        Button(onClick = {
                            cryptoService.generateKey()
                            keyGenerated = true
                        }) {
                            Text("Generate Key")
                        }
                    } else {
                        Text("Key generated ✓", color = Green80)
                        Spacer(Modifier.height(16.dp))
                        Text(
                            "Fingerprint: ${cryptoService.getPublicKeyFingerprint()}",
                            style = MaterialTheme.typography.bodyMedium,
                        )
                        Spacer(Modifier.height(24.dp))
                        Button(onClick = { step = SetupStep.GITHUB_CONFIG }) {
                            Text("Next: GitHub Setup")
                        }
                    }
                }

                SetupStep.GITHUB_CONFIG -> {
                    Text("GitHub Repository", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Create a new repo for your canary files, then enter the " +
                        "details below. Use a fine-grained PAT with contents:write scope.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(24.dp))

                    OutlinedTextField(
                        value = repoOwner,
                        onValueChange = { repoOwner = it },
                        label = { Text("Repo Owner (user or org)") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Spacer(Modifier.height(12.dp))
                    OutlinedTextField(
                        value = repoName,
                        onValueChange = { repoName = it },
                        label = { Text("Repo Name") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Spacer(Modifier.height(12.dp))
                    OutlinedTextField(
                        value = githubPat,
                        onValueChange = { githubPat = it },
                        label = { Text("Fine-grained PAT") },
                        singleLine = true,
                        visualTransformation = PasswordVisualTransformation(),
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Spacer(Modifier.height(24.dp))
                    Button(
                        onClick = {
                            prefsManager.repoOwner = repoOwner
                            prefsManager.repoName = repoName
                            prefsManager.githubPat = githubPat
                            step = SetupStep.PAIR_TAG
                        },
                        enabled = repoOwner.isNotBlank() && repoName.isNotBlank() && githubPat.isNotBlank(),
                    ) {
                        Text("Next: Pair RFID Tag")
                    }
                }

                SetupStep.PAIR_TAG -> {
                    Text("Pair RFID Sticker", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Tap your phone to the RFID sticker to pair it. " +
                        "A secret will be generated and written to the tag. " +
                        "This sticker is now your daily proof-of-life token.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(32.dp))

                    if (!tagPaired) {
                        Text(
                            "Waiting for NFC tag...",
                            style = MaterialTheme.typography.bodyLarge,
                            color = Green80,
                        )

                        LaunchedEffect(Unit) {
                            MainActivity.nfcIntentHandler = { intent ->
                                val tag: Tag? = intent.getParcelableExtra(NfcAdapter.EXTRA_TAG)
                                if (tag != null) {
                                    val secret = cryptoService.generateTagSecret()
                                    val success = nfcService.writeTagSecret(tag, secret)
                                    if (success) {
                                        tagPaired = true
                                        nfcMessage = "Tag paired successfully!"
                                    } else {
                                        nfcMessage = "Failed to write to tag"
                                    }
                                }
                            }
                        }
                    }

                    if (nfcMessage.isNotBlank()) {
                        Spacer(Modifier.height(12.dp))
                        Text(nfcMessage, color = Green80)
                    }

                    if (tagPaired) {
                        Spacer(Modifier.height(24.dp))
                        Button(onClick = { step = SetupStep.QR_BACKUP }) {
                            Text("Next: Backup QR")
                        }
                    }
                }

                SetupStep.QR_BACKUP -> {
                    Text("Backup QR Code", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Keep this QR code in a safe place. If you lose your " +
                        "RFID sticker, you can scan it to recover and pair a new one.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(24.dp))

                    val qrService = remember { com.canary.service.QrService() }
                    val passphrase = remember { qrService.generatePassphrase() }
                    val backupData = remember {
                        val pubKey = cryptoService.getPublicKeyPem()
                        qrService.encryptBackupData(pubKey.toByteArray(), passphrase)
                    }
                    val qrContent = remember {
                        android.util.Base64.encodeToString(backupData, android.util.Base64.NO_WRAP)
                    }
                    val qrBitmap = remember {
                        qrService.generateQrBitmap(qrContent, 512)
                    }

                    Card(
                        modifier = Modifier.size(280.dp),
                        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    ) {
                        val imageBitmap = qrBitmap.asImageBitmap()
                        Image(
                            bitmap = imageBitmap,
                            contentDescription = "Backup QR Code",
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp),
                        )
                    }

                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Passphrase (write this down):",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Text(
                        passphrase,
                        style = MaterialTheme.typography.headlineMedium,
                        color = Green80,
                    )
                    Spacer(Modifier.height(24.dp))
                    Button(onClick = {
                        prefsManager.isSetupComplete = true
                        onSetupComplete()
                    }) {
                        Text("Complete Setup")
                    }
                }

                SetupStep.DONE -> {}
            }
        }
    }
}
