package com.canary.ui.screens

import android.content.ContentValues
import android.content.Intent
import android.graphics.Bitmap
import android.nfc.NfcAdapter
import android.nfc.Tag
import android.os.Environment
import android.provider.MediaStore
import androidx.compose.foundation.Image
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.animation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.canary.MainActivity
import com.canary.data.PreferencesManager
import kotlinx.coroutines.withContext
import com.canary.service.CryptoService
import com.canary.service.GithubService
import com.canary.service.NfcService


enum class SetupStep {
    WELCOME,
    GENERATE_KEY,
    GITHUB_CONFIG,
    PAIR_TAG,
    RECOVERY_PHRASE,
    QR_BACKUP,
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SetupScreen(
    nfcService: NfcService,
    cryptoService: CryptoService,
    prefsManager: PreferencesManager,
    onSetupComplete: () -> Unit,
    onNavigateToRecovery: () -> Unit = {},
) {
    var step by remember { mutableStateOf(SetupStep.WELCOME) }
    var keyGenerated by remember { mutableStateOf(cryptoService.isKeyGenerated()) }
    var repoFull by remember { mutableStateOf("") }
    var githubPat by remember { mutableStateOf("") }
    var tagPaired by remember { mutableStateOf(false) }
    var nfcMessage by remember { mutableStateOf("") }

    Scaffold { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
        ) {
            when (step) {
                SetupStep.WELCOME -> {
                    Text("Canary", style = MaterialTheme.typography.displayLarge)
                    Spacer(Modifier.height(8.dp))
                    Text("Proof-of-life canary system", style = MaterialTheme.typography.bodyLarge)
                    Spacer(Modifier.height(32.dp))
                    Text(
                        "This app pairs with an RFID tag. Tap it daily to " +
                        "prove you're alive. Each canary is signed with your " +
                        "private key and anchored to the Bitcoin blockchain.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(32.dp))
                    Button(onClick = { step = SetupStep.GENERATE_KEY }) {
                        Text("Start Setup")
                    }
                    Spacer(Modifier.height(12.dp))
                    OutlinedButton(onClick = onNavigateToRecovery) {
                        Text("Scan Recovery QR")
                    }
                }

                SetupStep.GENERATE_KEY -> {
                    Text("Generate Signing Key", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "A unique Ed25519 keypair will be created and stored " +
                        "in your device's hardware-backed keystore. This key " +
                        "never leaves your phone.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(24.dp))

                    if (!keyGenerated) {
                        Button(onClick = {
                            cryptoService.generateKey()
                            keyGenerated = true
                        }) {
                            Text("Generate Key")
                        }
                    } else {
                        Text("Key generated ✓", color = MaterialTheme.colorScheme.primary)
                        Spacer(Modifier.height(16.dp))
                        Text(
                            "Fingerprint: ${cryptoService.getPublicKeyFingerprint()}",
                            style = MaterialTheme.typography.bodyMedium,
                        )
                        Spacer(Modifier.height(24.dp))
                        Button(onClick = { step = SetupStep.GITHUB_CONFIG }) {
                            Text("Next: GitHub Setup")
                        }
                    }
                }

                SetupStep.GITHUB_CONFIG -> {
                    Text("GitHub Repository", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Create a new repo for your canary files, then enter the " +
                        "details below. Use a fine-grained PAT with contents:write scope.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(24.dp))

                    OutlinedTextField(
                        value = repoFull,
                        onValueChange = { repoFull = it },
                        label = { Text("owner/repo") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                        placeholder = { Text("yourname/canary") },
                    )
                    Spacer(Modifier.height(12.dp))
                    OutlinedTextField(
                        value = githubPat,
                        onValueChange = { githubPat = it },
                        label = { Text("Fine-grained PAT") },
                        singleLine = true,
                        visualTransformation = PasswordVisualTransformation(),
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Spacer(Modifier.height(24.dp))
                    Button(
                        onClick = {
                            val parts = repoFull.trim().split("/")
                            if (parts.size == 2) {
                                prefsManager.repoOwner = parts[0].trim()
                                prefsManager.repoName = parts[1].trim()
                                prefsManager.githubPat = githubPat.trim()
                                step = SetupStep.PAIR_TAG
                            }
                        },
                        enabled = repoFull.matches(Regex(".+/.+")) && githubPat.isNotBlank(),
                    ) {
                        Text("Next: Pair RFID Tag")
                    }
                }

                SetupStep.PAIR_TAG -> {
                    Text("Pair RFID Sticker", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Tap your phone to the RFID tag to pair it. " +
                        "A secret will be generated and written to the tag. " +
                        "This tag is now your daily proof-of-life token.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(32.dp))

                    if (!tagPaired) {
                        Text(
                            "Waiting for NFC tag...",
                            style = MaterialTheme.typography.bodyLarge,
                            color = MaterialTheme.colorScheme.primary,
                        )

                        DisposableEffect(Unit) {
                            val handler: (Intent) -> Unit = { intent ->
                                try {
                                    val tag: Tag? = intent.getParcelableExtra(NfcAdapter.EXTRA_TAG)
                                    if (tag != null) {
                                        val secret = cryptoService.generateTagSecret()
                                        prefsManager.tagRawSecret = secret
                                        val success = nfcService.writeTagSecret(tag, secret)
                                        if (success) {
                                            tagPaired = true
                                            nfcMessage = "Tag paired successfully!"
                                        } else {
                                            nfcMessage = "Failed to write to tag"
                                        }
                                    } else {
                                        nfcMessage = "No NFC tag in intent"
                                    }
                                } catch (e: Exception) {
                                    nfcMessage = "NFC error: ${e.message}"
                                }
                            }
                            MainActivity.nfcIntentHandler.set(handler)
                            onDispose {
                                if (MainActivity.nfcIntentHandler.get() === handler) {
                                    MainActivity.nfcIntentHandler.set(null)
                                }
                            }
                        }
                    }

                    if (nfcMessage.isNotBlank()) {
                        Spacer(Modifier.height(12.dp))
                        Text(nfcMessage, color = MaterialTheme.colorScheme.primary)
                    }

                    if (tagPaired) {
                        Spacer(Modifier.height(24.dp))
                        Button(onClick = { step = SetupStep.RECOVERY_PHRASE }) {
                            Text("Next: Backup QR")
                        }
                    }
                }

                SetupStep.RECOVERY_PHRASE -> {
                    val qrService = remember { com.canary.service.QrService() }
                    val passphrase = remember {
                        val p = qrService.generatePassphrase()
                        prefsManager.recoveryMnemonic = p
                        p
                    }

                    Text("Recovery Passphrase", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Card(
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.errorContainer,
                        ),
                        modifier = Modifier.fillMaxWidth(),
                    ) {
                        Text(
                            "⚠  WRITE THIS DOWN  ⚠\n\n" +
                            "This is your recovery passphrase. Without it, " +
                            "you cannot recover your setup if you lose your " +
                            "phone or RFID tag. There is no other way to restore.",
                            modifier = Modifier.padding(16.dp),
                            color = MaterialTheme.colorScheme.onErrorContainer,
                            style = MaterialTheme.typography.bodyMedium,
                        )
                    }
                    Spacer(Modifier.height(24.dp))
                    Text(
                        passphrase,
                        style = MaterialTheme.typography.headlineSmall,
                        color = MaterialTheme.colorScheme.primary,
                    )
                    Spacer(Modifier.height(24.dp))
                    Button(onClick = { step = SetupStep.QR_BACKUP }) {
                        Text("I've Written It Down")
                    }
                }

                SetupStep.QR_BACKUP -> {
                    val qrService = remember { com.canary.service.QrService() }
                    val qrContent = remember {
                        "canary:v1:${prefsManager.repoOwner}/${prefsManager.repoName}"
                    }
                    val qrBitmap = remember {
                        qrService.generateQrBitmap(qrContent, 512)
                    }
                    var pushStatus by remember { mutableStateOf("Pushing recovery data...") }
                    var pushDone by remember { mutableStateOf(false) }

                    LaunchedEffect(Unit) {
                        withContext(kotlinx.coroutines.Dispatchers.IO) {
                        try {
                            val phrase = prefsManager.recoveryMnemonic
                            val configJson = org.json.JSONObject().apply {
                                put("pat", prefsManager.githubPat)
                                put("owner", prefsManager.repoOwner)
                                put("repo", prefsManager.repoName)
                            }.toString()
                            val encrypted = qrService.encryptBackupData(
                                configJson.toByteArray(),
                                phrase.split(" "),
                            )
                            val gh = GithubService(
                                prefsManager.githubPat,
                                prefsManager.repoOwner,
                                prefsManager.repoName,
                            )
                            val result = gh.pushRecoveryData(encrypted)
                            if (result.isSuccess) {
                                pushStatus = "Recovery data saved to GitHub ✓"
                            } else {
                                pushStatus = "Warning: could not push recovery data"
                            }
                            pushDone = true
                        } catch (_: Exception) {
                            pushStatus = "Warning: could not push recovery data"
                            pushDone = true
                        }
                        }
                    }

                    Text("Backup QR", style = MaterialTheme.typography.headlineMedium)
                    Spacer(Modifier.height(16.dp))
                    Text(
                        pushStatus,
                        style = MaterialTheme.typography.bodySmall,
                        color = if (pushStatus.startsWith("Warning")) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.primary,
                    )
                    Spacer(Modifier.height(16.dp))
                    Text(
                        "Scan this QR during recovery to tell the app which " +
                        "GitHub repo contains your encrypted recovery data.",
                        style = MaterialTheme.typography.bodyMedium,
                    )
                    Spacer(Modifier.height(24.dp))

                    Card(
                        modifier = Modifier.size(280.dp),
                        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                    ) {
                        val imageBitmap = qrBitmap.asImageBitmap()
                        Image(
                            bitmap = imageBitmap,
                            contentDescription = "Backup QR Code",
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(16.dp),
                        )
                    }

                    Spacer(Modifier.height(16.dp))

                    val context = LocalContext.current
                    var saveMessage by remember { mutableStateOf("") }
                    var qrSaved by remember { mutableStateOf(false) }
                    Button(
                        enabled = !qrSaved,
                        onClick = {
                        try {
                            val values = ContentValues().apply {
                                put(MediaStore.Images.Media.DISPLAY_NAME, "canary-backup.png")
                                put(MediaStore.Images.Media.MIME_TYPE, "image/png")
                                put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES)
                            }
                            val uri = context.contentResolver.insert(
                                MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values
                            )
                            if (uri != null) {
                                context.contentResolver.openOutputStream(uri)?.use { out ->
                                    qrBitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
                                }
                                qrSaved = true
                                saveMessage = "Saved to Pictures/canary-backup.png"
                            } else {
                                saveMessage = "Failed to save"
                            }
                        } catch (e: Exception) {
                            saveMessage = "Save error: ${e.message}"
                        }
                    }) {
                        Text("Save QR to Gallery")
                    }

                    if (saveMessage.isNotBlank()) {
                        Text(
                            saveMessage,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.primary,
                        )
                    }

                    Spacer(Modifier.height(16.dp))
                    Button(
                        onClick = {
                            prefsManager.isSetupComplete = true
                            onSetupComplete()
                        },
                        enabled = pushDone,
                    ) {
                        Text(if (pushDone) "Complete Setup" else "Uploading recovery data...")
                    }
                }
            }
        }
    }
}
